spring:
  config:
    import: file:env.properties
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  application:
    name: backend
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      lifetime: ${JWT_LIFETIME}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.security: DEBUG
server:
  port: ${SERVER_PORT}
